# /actions/commits/action.yml

name: 'local date Action'
description: 'Get the previous month or week from UTC'
author: 'im-soga'
inputs:
  utc:
    description: 'UTC'
    required: true
    default: ''
  type:
    description: 'type of output(month or week)'
    required: true
    default: ''
  timezone:
    description: 'timezone'
    required: true
    default: ''
  weekday:
    description: 'weekday'
    required: false
    default: ''
outputs:
  first:
    description: 'first day of month or week'
    #value: ${{ steps.localdate.outputs.first }}
  last:
    description: 'last day of month or week'
    #value: ${{ steps.localdate.outputs.last }}
runs:
  using: 'docker'
  image: 'Dockerfile'
