name: Build Container

on:
  push:
    branches:
      - main
#    tags:
#      - 'v*'

jobs:
  build_and_push:
    strategy:
      matrix:
        folder: [notion]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        id: buildx 
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define the Version
        id: defver
        run: |
          # tag = date & time (JST)
          VERSION=$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.folder }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.folder }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ matrix.folder }}:${{ steps.defver.outputs.VERSION }}
            ghcr.io/${{ github.repository }}/${{ matrix.folder }}:latest
