name: Monthly issue metrics
on:
  workflow_dispatch:
    inputs:
        repo:
            description: 'Repository name'
            required: true
            default: 'im-dev-cnts'
        owner:
            description: 'Repository owner'
            required: true
            default: 'b2bplatform'
        from:
            description: 'Start date'
            required: true
            default: '2023-01-01'
        to:
            description: 'End date'
            required: true
            default: '2023-12-31'
  schedule:
    - cron: '3 2 1 * *'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Run issue-metrics tool for issues and prs opened in a specific period
      id: issue-metrics
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        SEARCH_QUERY: 'repo:${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }} is:issue created:${{ github.event.inputs.from }}..${{ github.event.inputs.to }}'

    # JSON output
    - name: Print output of issue metrics tool
      run: echo "${{ steps.issue-metrics.outputs.metrics }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./issue_metrics.json
        asset_name: issue-metrics
        asset_content_type: text/json

    #- name: Create issue for opend issues and prs
    #  uses: peter-evans/create-issue-from-file@v4
    #  with:
    #    title: 'Monthly issue metrics'
    #    content-filepath: ./issue_metrics.md

    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MY_ACCESS_TOKEN }}

    - name: get commit infos
      uses: ./.github/actions/commits
      with:
        ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        REPO_OWNER: ${{ github.event.inputs.owner }}
        REPO_NAME: ${{ github.event.inputs.repo }}
  