name: test private container action
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  metrics_matrix:
    strategy:
      matrix:
        repo: ['metrics-test']
        owner: ['ebagos']
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: b2bplatform/metrics-test

      - name: Get current date and time
        env: 
          TZ: "UTC" # タイムゾーンを指定
        id: date
        #run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。

      - name: Get previous week
        id: weekly
        uses: ./.github/actions/localdate
        env:
          TYPE: 'week'
          UTC: ${{ steps.date.outputs.date }}
          WEEKDAY: '0'
          TIMEZONE: 'Asia/Tokyo'

      - name: create notion entry
        uses: ./.github/actions/entry
        id: entry
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TITLE: '${{ matrix.repo }} weekly metrics'

      - name: make commit page
        uses: ghcr.ioebagos/metrics-test/commits:latest
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          FROM_DATE: ${{ steps.weekly.outputs.first }}
          TO_DATE: ${{ steps.weekly.outputs.last }}
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          TITLE: '${{ matrix.repo }} commits'
          TIMEZONE: 'Asia/Tokyo'
  