name: Weekly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 * * 0' # every Sunday 2:03am UTC

permissions:
  issues: write
  pull-requests: read

jobs:
  metrics_matrix:
    strategy:
      matrix:
        repo: ['metrics-test']
        owner: ['ebagos']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: ebagos/metrics-test

      - name: Get current date and time
        env: 
          TZ: "UTC" # タイムゾーンを指定
        id: date
        #run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。

      - name: Get previous week
        id: weekly
        uses: ./.github/actions/localdate
        env:
          TYPE: 'week'
          UTC: ${{ steps.date.outputs.date }}
          WEEKDAY: '0'
          TIMEZONE: 'Asia/Tokyo'

      - name: Output from date test
        run: echo "${{ steps.weekly.outputs.first }}"

      - name: create notion entry
        uses: ./.github/actions/entry
        id: entry
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: 3d1e60c6207241b09c1aae48750f0833
          TITLE: '${{ matrix.repo }} weekly metrics'

      - name: make commit page
        uses: ./.github/actions/commit
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          FROM_DATE: ${{ steps.weekly.outputs.first }}
          TO_DATE: ${{ steps.weekly.outputs.last }}
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          TITLE: '${{ matrix.repo }} commits'
  
      - name: Run issue-metrics tool for issues opened in a specific period
        id: issue-metrics-created
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          SEARCH_QUERY: 'repo:${{ matrix.owner }}/${{ matrix.repo }} is:issue created:${{ steps.weekly.outputs.first }}..${{ steps.weekly.outputs.last }}'

      - name upload issue-metrics-created
        uses: ./.github/actions/upload
        with:
          name: issue-metrics
          file: issue_metrics.md

      - name: markdown to notion - 1
        uses: ./.github/actions/notion
        env:
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          MARKDOWN_FILENAME: issue_metrics.md
          TITLE: '${{ matrix.repo }}: issue created'
          TAGS: issue,created

      - name: Run issue-metrics tool for prs opened in a specific period
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          SEARCH_QUERY: 'repo:${{ matrix.owner }}/${{ matrix.repo }} is:pr created:${{ steps.weekly.outputs.first }}..${{ steps.weekly.outputs.last }}'

      - name: markdown to notion - 2
        uses: ./.github/actions/notion
        env:
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          MARKDOWN_FILENAME: issue_metrics.md
          TITLE: '${{ matrix.repo }}: pr created'
          TAGS: pr,created
  
      - name: Run issue-metrics tool for prs opened in a specific period
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          SEARCH_QUERY: 'repo:${{ matrix.owner }}/${{ matrix.repo }} is:issue closed:${{ steps.weekly.outputs.first }}..${{ steps.weekly.outputs.last }}'

      - name: markdown to notion - 3
        uses: ./.github/actions/notion
        env:
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          MARKDOWN_FILENAME: issue_metrics.md
          TITLE: '${{ matrix.repo }}: issue closed'
          TAGS: issue,closed
  
      - name: Run issue-metrics tool for prs opened in a specific period
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          SEARCH_QUERY: 'repo:${{ matrix.owner }}/${{ matrix.repo }} is:pr closed:${{ steps.weekly.outputs.first }}..${{ steps.weekly.outputs.last }}'
  
      - name: markdown to notion - 4
        uses: ./.github/actions/notion
        env:
          REPO_OWNER: ${{ matrix.owner }}
          REPO_NAME: ${{ matrix.repo }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ steps.entry.outputs.database_id }}
          MARKDOWN_FILENAME: issue_metrics.md
          TITLE: '${{ matrix.repo }}: pr closed'
          TAGS: pr,closed
  